version: '3.9'

services:
  backend:
    build: ./backend
    container_name: medstagram-backend
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: medstagram-frontend
    volumes:
      - ./frontend:/app
    ports:
      - '5173:5173'
    env_file:
      - ./frontend/.env

  db:
    image: postgres:15
    container_name: medstagram-db
    restart: always
    environment:
      POSTGRES_USER: meduser
      POSTGRES_PASSWORD: medpass
      POSTGRES_DB: medstagram
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
